// <auto-generated />
using System;
using GraphQlDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQlDemo.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10");

            modelBuilder.Entity("GraphQlDemo.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marijn Haverbeke"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Addy Osmani"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Axel Rauschmayer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Eric Elliott"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nicholas C. Zakas"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kyle Simpson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Richard E. Silverman"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Glenn Block, et al."
                        });
                });

            modelBuilder.Entity("GraphQlDemo.Models.Book", b =>
                {
                    b.Property<string>("Isbn");

                    b.Property<int>("AuthorId");

                    b.Property<string>("Description");

                    b.Property<int>("Pages");

                    b.Property<DateTime>("Published");

                    b.Property<int>("PublisherId");

                    b.Property<string>("SubTitle");

                    b.Property<string>("Title");

                    b.Property<string>("Website");

                    b.HasKey("Isbn");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Isbn = "9781593275846",
                            AuthorId = 1,
                            Description = "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
                            Pages = 472,
                            Published = new DateTime(2014, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            SubTitle = "A Modern Introduction to Programming",
                            Title = "Eloquent JavaScript, Second Edition",
                            Website = "http://eloquentjavascript.net/"
                        },
                        new
                        {
                            Isbn = "9781449331818",
                            AuthorId = 2,
                            Description = "With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-date with the latest best practices, this book is for you.",
                            Pages = 254,
                            Published = new DateTime(2012, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            SubTitle = "A JavaScript and jQuery Developer's Guide",
                            Title = "Learning JavaScript Design Patterns",
                            Website = "http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/"
                        },
                        new
                        {
                            Isbn = "9781449365035",
                            AuthorId = 3,
                            Description = "Like it or not, JavaScript is everywhere these days-from browser to server to mobile-and now you, too, need to learn the language or dive deeper than you have. This concise book guides you into and through JavaScript, written by a veteran programmer who once found himself in the same position.",
                            Pages = 460,
                            Published = new DateTime(2014, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            SubTitle = "An In-Depth Guide for Programmers",
                            Title = "Speaking JavaScript",
                            Website = "http://speakingjs.com/"
                        },
                        new
                        {
                            Isbn = "9781491950296",
                            AuthorId = 4,
                            Description = "Take advantage of JavaScript's power to build robust web-scale or enterprise applications that are easy to extend and maintain. By applying the design patterns outlined in this practical book, experienced JavaScript developers will learn how to write flexible and resilient code that's easier-yes, easier-to work with as your code base grows.",
                            Pages = 254,
                            Published = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            SubTitle = "Robust Web Architecture with Node, HTML5, and Modern JS Libraries",
                            Title = "Programming JavaScript Applications",
                            Website = "http://chimera.labs.oreilly.com/books/1234000000262/index.html"
                        },
                        new
                        {
                            Isbn = "9781593277574",
                            AuthorId = 5,
                            Description = "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript.",
                            Pages = 352,
                            Published = new DateTime(2016, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            SubTitle = "The Definitive Guide for JavaScript Developers",
                            Title = "Understanding ECMAScript 6",
                            Website = "https://leanpub.com/understandinges6/read"
                        },
                        new
                        {
                            Isbn = "9781491904244",
                            AuthorId = 6,
                            Description = "No matter how much experience you have with JavaScript, odds are you don�t fully understand the language. As part of the \"You Don�t Know JS\" series, this compact guide focuses on new features available in ECMAScript 6 (ES6), the latest version of the standard upon which JavaScript is built.",
                            Pages = 278,
                            Published = new DateTime(2015, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            SubTitle = "ES6 & Beyond",
                            Title = "You Don't Know JS",
                            Website = "https://github.com/getify/You-Dont-Know-JS/tree/master/es6 & beyond"
                        },
                        new
                        {
                            Isbn = "9781449325862",
                            AuthorId = 7,
                            Description = "This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git experience.",
                            Pages = 234,
                            Published = new DateTime(2013, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            SubTitle = "A Working Introduction",
                            Title = "Git Pocket Guide",
                            Website = "http://chimera.labs.oreilly.com/books/1230000000561/index.html"
                        },
                        new
                        {
                            Isbn = "9781449337711",
                            AuthorId = 8,
                            Description = "Design and build Web APIs for a broad range of clients�including browsers and mobile devices�that can adapt to change over time. This practical, hands-on guide takes you through the theory and tools you need to build evolvable HTTP services with Microsoft�s ASP.NET Web API framework. In the process, you�ll learn how design and implement a real-world Web API.",
                            Pages = 538,
                            Published = new DateTime(2014, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            SubTitle = "Harnessing the Power of the Web",
                            Title = "Designing Evolvable Web APIs with ASP.NET",
                            Website = "http://chimera.labs.oreilly.com/books/1234000001708/index.html"
                        });
                });

            modelBuilder.Entity("GraphQlDemo.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "No Starch Press"
                        },
                        new
                        {
                            Id = 2,
                            Name = "O'Reilly Media"
                        });
                });

            modelBuilder.Entity("GraphQlDemo.Models.Book", b =>
                {
                    b.HasOne("GraphQlDemo.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphQlDemo.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
